name: First Workflow
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Job-1 Step-1
        run: echo 'This is job-1 step-1'
      - name: Job-1 Step-2
        run: echo 'This is job-1 step-2'
      - name: Job-1 Step-3
        run: echo 'This is job-1 step-3'
  job-2:
    runs-on: windows-latest
    steps:
      - name: Job-2 Step-1
        run: echo 'This is job-2 step-1'
      - name: Job-2 Step-2
        run: echo 'This is job-2 step-2'
      - name: Job-2 Step-3
        run: echo 'This is job-2 step-3'
